"""
Govee devices exported from your account.
Generated by govee-python-sdk.

Import devices directly:
    from govee_devices import ground2_machine
"""
from govee.models import Device


ground1_elevator = Device(
    id="7D:DE:C8:39:32:33:3E:3B",
    name="Ground1 Elevator",
    sku="H7050",
    ip=None,
    capabilities=['on_off', 'range', 'segment_color_setting', 'color_setting', 'color_setting', 'dynamic_scene', 'dynamic_scene'],
    metadata={'type': 'devices.types.light', 'retrievable': None}
)

string_lights_1 = Device(
    id="80:DC:D7:37:32:34:64:5E",
    name="String Lights 1",
    sku="H7021",
    ip=None,
    capabilities=['on_off', 'toggle', 'range', 'segment_color_setting', 'segment_color_setting', 'color_setting', 'color_setting', 'dynamic_scene', 'music_setting', 'dynamic_scene'],
    metadata={'type': 'devices.types.light', 'retrievable': None}
)

xmas_tree_bottom = Device(
    id="18:84:F5:1A:1B:BA:D7:4B",
    name="Xmas Tree - Bottom",
    sku="H70C2",
    ip=None,
    capabilities=['on_off', 'toggle', 'range', 'segment_color_setting', 'segment_color_setting', 'color_setting', 'color_setting', 'dynamic_scene', 'music_setting', 'dynamic_scene', 'dynamic_scene', 'toggle'],
    metadata={'type': 'devices.types.light', 'retrievable': None}
)

xmas_tree_top = Device(
    id="22:A4:C2:5E:14:56:C6:81",
    name="Xmas Tree - Top",
    sku="H70C1",
    ip=None,
    capabilities=['on_off', 'toggle', 'range', 'segment_color_setting', 'segment_color_setting', 'color_setting', 'color_setting', 'dynamic_scene', 'music_setting', 'dynamic_scene', 'dynamic_scene', 'toggle'],
    metadata={'type': 'devices.types.light', 'retrievable': None}
)

flood1_pauly_balcony = Device(
    id="9B:CD:C4:35:33:33:3A:79",
    name="Flood1 Pauly Balcony",
    sku="H7060",
    ip=None,
    capabilities=['on_off', 'range', 'segment_color_setting', 'segment_color_setting', 'color_setting', 'color_setting', 'dynamic_scene', 'dynamic_scene'],
    metadata={'type': 'devices.types.light', 'retrievable': None}
)

jimmy_garage_left = Device(
    id="45:1B:60:74:F4:66:AD:90",
    name="Jimmy Garage Left",
    sku="H6008",
    ip=None,
    capabilities=['on_off', 'range', 'color_setting', 'color_setting', 'dynamic_scene', 'dynamic_scene'],
    metadata={'type': 'devices.types.light', 'retrievable': None}
)

jimmy_garage_right = Device(
    id="D7:B5:60:74:F4:6D:05:EA",
    name="Jimmy Garage Right",
    sku="H6008",
    ip=None,
    capabilities=['on_off', 'range', 'color_setting', 'color_setting', 'dynamic_scene', 'dynamic_scene'],
    metadata={'type': 'devices.types.light', 'retrievable': None}
)

peter_garage_left = Device(
    id="3D:7F:60:74:F4:67:E4:28",
    name="Peter Garage Left",
    sku="H6008",
    ip=None,
    capabilities=['on_off', 'range', 'color_setting', 'color_setting', 'dynamic_scene', 'dynamic_scene'],
    metadata={'type': 'devices.types.light', 'retrievable': None}
)

peter_garage_right = Device(
    id="CD:12:60:74:F4:64:DD:B4",
    name="Peter Garage Right",
    sku="H6008",
    ip=None,
    capabilities=['on_off', 'range', 'color_setting', 'color_setting', 'dynamic_scene', 'dynamic_scene'],
    metadata={'type': 'devices.types.light', 'retrievable': None}
)

connie_garage_left = Device(
    id="14:15:60:74:F4:07:99:39",
    name="Connie Garage Left",
    sku="H6008",
    ip=None,
    capabilities=['on_off', 'range', 'color_setting', 'color_setting', 'dynamic_scene', 'dynamic_scene'],
    metadata={'type': 'devices.types.light', 'retrievable': None}
)

connie_garage_right = Device(
    id="1E:61:60:74:F4:09:EB:FA",
    name="Connie Garage Right",
    sku="H6008",
    ip=None,
    capabilities=['on_off', 'range', 'color_setting', 'color_setting', 'dynamic_scene', 'dynamic_scene'],
    metadata={'type': 'devices.types.light', 'retrievable': None}
)

erik_garage_left = Device(
    id="21:8A:60:74:F4:09:E7:D2",
    name="Erik Garage Left",
    sku="H6008",
    ip=None,
    capabilities=['on_off', 'range', 'color_setting', 'color_setting', 'dynamic_scene', 'dynamic_scene'],
    metadata={'type': 'devices.types.light', 'retrievable': None}
)

erik_garage_right = Device(
    id="15:9C:60:74:F4:07:4D:0A",
    name="Erik Garage Right",
    sku="H6008",
    ip=None,
    capabilities=['on_off', 'range', 'color_setting', 'color_setting', 'dynamic_scene', 'dynamic_scene'],
    metadata={'type': 'devices.types.light', 'retrievable': None}
)

xmas_string_lights_1 = Device(
    id="45:DB:C5:D4:6A:A3:A2:80",
    name="Xmas String Lights 1",
    sku="H70CB",
    ip=None,
    capabilities=['on_off', 'toggle', 'range', 'segment_color_setting', 'segment_color_setting', 'color_setting', 'color_setting', 'dynamic_scene', 'music_setting', 'dynamic_scene', 'dynamic_scene'],
    metadata={'type': 'devices.types.light', 'retrievable': None}
)

xmas_tree_middle = Device(
    id="44:31:E4:08:D5:AE:8A:FD",
    name="Xmas Tree - Middle",
    sku="H70CB",
    ip=None,
    capabilities=['on_off', 'toggle', 'range', 'segment_color_setting', 'segment_color_setting', 'color_setting', 'color_setting', 'dynamic_scene', 'music_setting', 'dynamic_scene', 'dynamic_scene'],
    metadata={'type': 'devices.types.light', 'retrievable': None}
)

jimmy_balcony_left = Device(
    id="22:51:60:74:F4:6F:61:D0",
    name="Jimmy Balcony Left",
    sku="H6008",
    ip=None,
    capabilities=['on_off', 'range', 'color_setting', 'color_setting', 'dynamic_scene', 'dynamic_scene'],
    metadata={'type': 'devices.types.light', 'retrievable': None}
)

jimmy_balcony_right = Device(
    id="27:3C:60:74:F4:5D:DC:EA",
    name="Jimmy Balcony Right",
    sku="H6008",
    ip=None,
    capabilities=['on_off', 'range', 'color_setting', 'color_setting', 'dynamic_scene', 'dynamic_scene'],
    metadata={'type': 'devices.types.light', 'retrievable': None}
)

jimmy_balcony_rear = Device(
    id="63:07:60:74:F4:70:0A:50",
    name="Jimmy Balcony Rear",
    sku="H6008",
    ip=None,
    capabilities=['on_off', 'range', 'color_setting', 'color_setting', 'dynamic_scene', 'dynamic_scene'],
    metadata={'type': 'devices.types.light', 'retrievable': None}
)

cloud_led_strip = Device(
    id="1C:D2:CA:35:34:35:32:08",
    name="Cloud LED Strip",
    sku="H61E0",
    ip=None,
    capabilities=['on_off', 'toggle', 'range', 'segment_color_setting', 'segment_color_setting', 'color_setting', 'color_setting', 'dynamic_scene', 'music_setting', 'dynamic_scene', 'dynamic_scene', 'toggle'],
    metadata={'type': 'devices.types.light', 'retrievable': None}
)

triad_connie2 = Device(
    id="13:AC:C9:F0:85:06:5A:74",
    name="Triad Connie2",
    sku="H7063",
    ip=None,
    capabilities=['on_off', 'range', 'segment_color_setting', 'segment_color_setting', 'color_setting', 'color_setting', 'dynamic_scene', 'dynamic_scene', 'toggle', 'toggle'],
    metadata={'type': 'devices.types.light', 'retrievable': None}
)

pauly_garage_left = Device(
    id="F2:4E:60:74:F4:C5:B4:36",
    name="Pauly Garage Left",
    sku="H6008",
    ip=None,
    capabilities=['on_off', 'range', 'color_setting', 'color_setting', 'dynamic_scene', 'dynamic_scene'],
    metadata={'type': 'devices.types.light', 'retrievable': None}
)

pauly_garage_right = Device(
    id="14:95:60:74:F4:CF:39:D4",
    name="Pauly Garage Right",
    sku="H6008",
    ip=None,
    capabilities=['on_off', 'range', 'color_setting', 'color_setting', 'dynamic_scene', 'dynamic_scene'],
    metadata={'type': 'devices.types.light', 'retrievable': None}
)

jenn_garage_left = Device(
    id="24:0B:60:74:F4:B3:1C:86",
    name="Jenn Garage Left",
    sku="H6008",
    ip=None,
    capabilities=['on_off', 'range', 'color_setting', 'color_setting', 'dynamic_scene', 'dynamic_scene'],
    metadata={'type': 'devices.types.light', 'retrievable': None}
)

jenn_garage_right = Device(
    id="24:D4:60:74:F4:AB:B4:8C",
    name="Jenn Garage Right",
    sku="H6008",
    ip=None,
    capabilities=['on_off', 'range', 'color_setting', 'color_setting', 'dynamic_scene', 'dynamic_scene'],
    metadata={'type': 'devices.types.light', 'retrievable': None}
)

jason_garage_left = Device(
    id="18:B1:60:74:F4:C6:68:64",
    name="Jason Garage Left",
    sku="H6008",
    ip=None,
    capabilities=['on_off', 'range', 'color_setting', 'color_setting', 'dynamic_scene', 'dynamic_scene'],
    metadata={'type': 'devices.types.light', 'retrievable': None}
)

jason_garage_right = Device(
    id="15:9F:60:74:F4:B7:BD:88",
    name="Jason Garage Right",
    sku="H6008",
    ip=None,
    capabilities=['on_off', 'range', 'color_setting', 'color_setting', 'dynamic_scene', 'dynamic_scene'],
    metadata={'type': 'devices.types.light', 'retrievable': None}
)

jeff_garage_left = Device(
    id="1A:73:60:74:F4:AC:8E:76",
    name="Jeff Garage Left",
    sku="H6008",
    ip=None,
    capabilities=['on_off', 'range', 'color_setting', 'color_setting', 'dynamic_scene', 'dynamic_scene'],
    metadata={'type': 'devices.types.light', 'retrievable': None}
)

jeff_garage_right = Device(
    id="2B:43:60:74:F4:B7:BD:BE",
    name="Jeff Garage Right",
    sku="H6008",
    ip=None,
    capabilities=['on_off', 'range', 'color_setting', 'color_setting', 'dynamic_scene', 'dynamic_scene'],
    metadata={'type': 'devices.types.light', 'retrievable': None}
)

plug_haze = Device(
    id="1C:59:60:74:F4:DF:B4:40",
    name="Plug Haze",
    sku="H5080",
    ip=None,
    capabilities=['on_off'],
    metadata={'type': 'devices.types.socket', 'retrievable': None}
)

plug_hawkins_lab = Device(
    id="12:05:60:74:F4:E7:4B:30",
    name="Plug Hawkins Lab",
    sku="H5080",
    ip=None,
    capabilities=['on_off'],
    metadata={'type': 'devices.types.socket', 'retrievable': None}
)

plug_jeff_lights = Device(
    id="14:60:60:74:F4:E8:04:CE",
    name="Plug Jeff Lights",
    sku="H5080",
    ip=None,
    capabilities=['on_off'],
    metadata={'type': 'devices.types.socket', 'retrievable': None}
)

plug_cerebro = Device(
    id="15:E7:60:74:F4:E6:8E:76",
    name="Plug Cerebro",
    sku="H5080",
    ip=None,
    capabilities=['on_off'],
    metadata={'type': 'devices.types.socket', 'retrievable': None}
)

triad_mind_flayer = Device(
    id="1E:13:C9:F0:82:06:68:3D",
    name="Triad Mind Flayer",
    sku="H7063",
    ip=None,
    capabilities=['on_off', 'range', 'segment_color_setting', 'segment_color_setting', 'color_setting', 'color_setting', 'dynamic_scene', 'dynamic_scene', 'toggle', 'toggle'],
    metadata={'type': 'devices.types.light', 'retrievable': None}
)

plug_blacklight = Device(
    id="44:7A:60:74:F4:D0:FE:0A",
    name="Plug Blacklight",
    sku="H5080",
    ip=None,
    capabilities=['on_off'],
    metadata={'type': 'devices.types.socket', 'retrievable': None}
)

plug_mall_sign = Device(
    id="11:30:60:74:F4:DE:6F:24",
    name="Plug Mall Sign",
    sku="H5080",
    ip=None,
    capabilities=['on_off'],
    metadata={'type': 'devices.types.socket', 'retrievable': None}
)

triad_gate1 = Device(
    id="0A:99:C9:F0:82:46:4A:32",
    name="Triad Gate1",
    sku="H7063",
    ip=None,
    capabilities=['on_off', 'range', 'segment_color_setting', 'segment_color_setting', 'color_setting', 'color_setting', 'dynamic_scene', 'dynamic_scene', 'toggle', 'toggle'],
    metadata={'type': 'devices.types.light', 'retrievable': None}
)

triad_gate2 = Device(
    id="22:06:C9:F0:85:06:33:7D",
    name="Triad Gate2",
    sku="H7063",
    ip=None,
    capabilities=['on_off', 'range', 'segment_color_setting', 'segment_color_setting', 'color_setting', 'color_setting', 'dynamic_scene', 'dynamic_scene', 'toggle', 'toggle'],
    metadata={'type': 'devices.types.light', 'retrievable': None}
)

plug_pauly = Device(
    id="19:F7:60:74:F4:D3:C4:6E",
    name="Plug Pauly",
    sku="H5080",
    ip=None,
    capabilities=['on_off'],
    metadata={'type': 'devices.types.socket', 'retrievable': None}
)

neon_laser_beam = Device(
    id="0D:D5:33:C4:46:20:8A:FF",
    name="Neon Laser Beam",
    sku="H61A8",
    ip=None,
    capabilities=['on_off', 'toggle', 'range', 'segment_color_setting', 'segment_color_setting', 'color_setting', 'color_setting', 'dynamic_scene', 'music_setting', 'dynamic_scene', 'dynamic_scene'],
    metadata={'type': 'devices.types.light', 'retrievable': None}
)

neon_elevator = Device(
    id="0F:D1:06:04:46:65:88:FF",
    name="Neon Elevator",
    sku="H61A8",
    ip=None,
    capabilities=['on_off', 'toggle', 'range', 'segment_color_setting', 'segment_color_setting', 'color_setting', 'color_setting', 'dynamic_scene', 'music_setting', 'dynamic_scene', 'dynamic_scene'],
    metadata={'type': 'devices.types.light', 'retrievable': None}
)

plug_promethium = Device(
    id="31:65:60:74:F4:DE:A1:72",
    name="Plug Promethium",
    sku="H5080",
    ip=None,
    capabilities=['on_off'],
    metadata={'type': 'devices.types.socket', 'retrievable': None}
)

string_laser_beam = Device(
    id="22:2C:F0:9F:A3:EA:39:8B",
    name="String Laser Beam",
    sku="H70C2",
    ip=None,
    capabilities=['on_off', 'toggle', 'range', 'segment_color_setting', 'segment_color_setting', 'color_setting', 'color_setting', 'dynamic_scene', 'music_setting', 'dynamic_scene', 'dynamic_scene', 'toggle'],
    metadata={'type': 'devices.types.light', 'retrievable': None}
)

strip_machine_core = Device(
    id="82:F8:D4:0F:43:C6:35:86",
    name="Strip Machine Core",
    sku="H70A2",
    ip=None,
    capabilities=['on_off', 'toggle', 'range', 'segment_color_setting', 'segment_color_setting', 'color_setting', 'color_setting', 'dynamic_scene', 'music_setting', 'dynamic_scene', 'dynamic_scene'],
    metadata={'type': 'devices.types.light', 'retrievable': None}
)

spotlight1_sign = Device(
    id="97:2F:D0:05:85:C6:3D:7A",
    name="Spotlight1 Sign",
    sku="H7065",
    ip=None,
    capabilities=['on_off', 'toggle', 'range', 'segment_color_setting', 'segment_color_setting', 'color_setting', 'color_setting', 'dynamic_scene', 'music_setting', 'dynamic_scene'],
    metadata={'type': 'devices.types.light', 'retrievable': None}
)

ground2_machine = Device(
    id="0E:BE:D6:50:83:C6:15:1F",
    name="Ground2 Machine",
    sku="H7052",
    ip="192.168.10.26",
    capabilities=['on_off', 'range', 'segment_color_setting', 'segment_color_setting', 'color_setting', 'color_setting', 'music_setting', 'dynamic_scene', 'dynamic_scene'],
    metadata={'type': 'devices.types.light', 'retrievable': None}
)

flood2_jeff_balcony = Device(
    id="0E:41:D2:2D:44:C6:58:55",
    name="Flood2 Jeff Balcony",
    sku="H7057",
    ip=None,
    capabilities=['on_off', 'toggle', 'toggle', 'range', 'segment_color_setting', 'segment_color_setting', 'color_setting', 'color_setting', 'dynamic_scene', 'music_setting', 'dynamic_scene', 'dynamic_scene'],
    metadata={'type': 'devices.types.light', 'retrievable': None}
)

string_bulbs_peter = Device(
    id="11:93:DB:E6:C6:06:49:30",
    name="String Bulbs Peter",
    sku="H7025",
    ip=None,
    capabilities=['on_off', 'range', 'color_setting', 'color_setting', 'dynamic_scene', 'music_setting', 'segment_color_setting', 'segment_color_setting', 'dynamic_scene', 'dynamic_scene'],
    metadata={'type': 'devices.types.light', 'retrievable': None}
)

erik_balcony_right = Device(
    id="2F:12:98:17:3C:E0:D2:30",
    name="Erik Balcony Right",
    sku="H6008",
    ip=None,
    capabilities=['on_off', 'range', 'color_setting', 'color_setting', 'dynamic_scene', 'dynamic_scene'],
    metadata={'type': 'devices.types.light', 'retrievable': None}
)

erik_balcony_left = Device(
    id="B2:D9:98:17:3C:E1:E0:D8",
    name="Erik Balcony Left",
    sku="H6008",
    ip=None,
    capabilities=['on_off', 'range', 'color_setting', 'color_setting', 'dynamic_scene', 'dynamic_scene'],
    metadata={'type': 'devices.types.light', 'retrievable': None}
)

jenn_balcony_bulb = Device(
    id="3E:3D:98:17:3C:D8:D1:34",
    name="Jenn Balcony Bulb",
    sku="H6008",
    ip=None,
    capabilities=['on_off', 'range', 'color_setting', 'color_setting', 'dynamic_scene', 'dynamic_scene'],
    metadata={'type': 'devices.types.light', 'retrievable': None}
)

peter_balcony_right = Device(
    id="1E:61:D0:C9:07:38:18:6A",
    name="Peter Balcony Right",
    sku="H6008",
    ip=None,
    capabilities=['on_off', 'range', 'color_setting', 'color_setting', 'dynamic_scene', 'dynamic_scene'],
    metadata={'type': 'devices.types.light', 'retrievable': None}
)

peter_balcony_left = Device(
    id="47:1B:D0:C9:07:32:04:2E",
    name="Peter Balcony Left",
    sku="H6008",
    ip=None,
    capabilities=['on_off', 'range', 'color_setting', 'color_setting', 'dynamic_scene', 'dynamic_scene'],
    metadata={'type': 'devices.types.light', 'retrievable': None}
)

pauly_balcony_bulb = Device(
    id="31:7C:98:17:3C:D8:CB:DC",
    name="Pauly Balcony Bulb",
    sku="H6008",
    ip=None,
    capabilities=['on_off', 'range', 'color_setting', 'color_setting', 'dynamic_scene', 'dynamic_scene'],
    metadata={'type': 'devices.types.light', 'retrievable': None}
)

spotlight2_machine = Device(
    id="0E:4B:D6:50:85:06:0E:50",
    name="Spotlight2 Machine",
    sku="H7094",
    ip=None,
    capabilities=['on_off', 'range', 'color_setting', 'color_setting', 'dynamic_scene', 'music_setting', 'segment_color_setting', 'segment_color_setting', 'dynamic_scene', 'dynamic_scene'],
    metadata={'type': 'devices.types.light', 'retrievable': None}
)

neon_peter = Device(
    id="17:D1:06:01:C6:29:30:FF",
    name="Neon Peter",
    sku="H61A8",
    ip=None,
    capabilities=['on_off', 'toggle', 'range', 'segment_color_setting', 'segment_color_setting', 'color_setting', 'color_setting', 'dynamic_scene', 'music_setting', 'dynamic_scene', 'dynamic_scene'],
    metadata={'type': 'devices.types.light', 'retrievable': None}
)

neon_jenn = Device(
    id="0C:D0:C8:45:46:5D:18:FF",
    name="Neon Jenn",
    sku="H61A8",
    ip=None,
    capabilities=['on_off', 'toggle', 'range', 'segment_color_setting', 'segment_color_setting', 'color_setting', 'color_setting', 'dynamic_scene', 'music_setting', 'dynamic_scene', 'dynamic_scene'],
    metadata={'type': 'devices.types.light', 'retrievable': None}
)

neon_connie = Device(
    id="45:D4:39:C3:06:63:42:FF",
    name="Neon Connie",
    sku="H61A8",
    ip=None,
    capabilities=['on_off', 'toggle', 'range', 'segment_color_setting', 'segment_color_setting', 'color_setting', 'color_setting', 'dynamic_scene', 'music_setting', 'dynamic_scene', 'dynamic_scene'],
    metadata={'type': 'devices.types.light', 'retrievable': None}
)

flood2_jenn = Device(
    id="0E:9E:D3:2D:42:46:07:6C",
    name="Flood2 Jenn",
    sku="H7057",
    ip=None,
    capabilities=['on_off', 'toggle', 'toggle', 'range', 'segment_color_setting', 'segment_color_setting', 'color_setting', 'color_setting', 'dynamic_scene', 'music_setting', 'dynamic_scene', 'dynamic_scene'],
    metadata={'type': 'devices.types.light', 'retrievable': None}
)

bulb_cerebro = Device(
    id="24:0E:D0:C9:07:1E:1F:BA",
    name="Bulb Cerebro",
    sku="H6008",
    ip=None,
    capabilities=['on_off', 'range', 'color_setting', 'color_setting', 'dynamic_scene', 'dynamic_scene'],
    metadata={'type': 'devices.types.light', 'retrievable': None}
)

garages_south = Device(
    id="8250126",
    name="Garages - South",
    sku="BaseGroup",
    ip=None,
    capabilities=['on_off'],
    metadata={'type': None, 'retrievable': None}
)

garages_north = Device(
    id="8249518",
    name="Garages - North",
    sku="BaseGroup",
    ip=None,
    capabilities=['on_off'],
    metadata={'type': None, 'retrievable': None}
)

garage_lights = Device(
    id="8953563",
    name="Garage Lights",
    sku="SameModeGroup",
    ip=None,
    capabilities=['on_off'],
    metadata={'type': None, 'retrievable': None}
)

xmas_tree_lights = Device(
    id="8953259",
    name="Xmas Tree Lights",
    sku="SameModeGroup",
    ip=None,
    capabilities=['on_off'],
    metadata={'type': None, 'retrievable': None}
)

__all__ = [
    "ground1_elevator",
    "string_lights_1",
    "xmas_tree_bottom",
    "xmas_tree_top",
    "flood1_pauly_balcony",
    "jimmy_garage_left",
    "jimmy_garage_right",
    "peter_garage_left",
    "peter_garage_right",
    "connie_garage_left",
    "connie_garage_right",
    "erik_garage_left",
    "erik_garage_right",
    "xmas_string_lights_1",
    "xmas_tree_middle",
    "jimmy_balcony_left",
    "jimmy_balcony_right",
    "jimmy_balcony_rear",
    "cloud_led_strip",
    "triad_connie2",
    "pauly_garage_left",
    "pauly_garage_right",
    "jenn_garage_left",
    "jenn_garage_right",
    "jason_garage_left",
    "jason_garage_right",
    "jeff_garage_left",
    "jeff_garage_right",
    "plug_haze",
    "plug_hawkins_lab",
    "plug_jeff_lights",
    "plug_cerebro",
    "triad_mind_flayer",
    "plug_blacklight",
    "plug_mall_sign",
    "triad_gate1",
    "triad_gate2",
    "plug_pauly",
    "neon_laser_beam",
    "neon_elevator",
    "plug_promethium",
    "string_laser_beam",
    "strip_machine_core",
    "spotlight1_sign",
    "ground2_machine",
    "flood2_jeff_balcony",
    "string_bulbs_peter",
    "erik_balcony_right",
    "erik_balcony_left",
    "jenn_balcony_bulb",
    "peter_balcony_right",
    "peter_balcony_left",
    "pauly_balcony_bulb",
    "spotlight2_machine",
    "neon_peter",
    "neon_jenn",
    "neon_connie",
    "flood2_jenn",
    "bulb_cerebro",
    "garages_south",
    "garages_north",
    "garage_lights",
    "xmas_tree_lights",
]